# Generated by Django 3.2.4 on 2023-12-21 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roleresourcemapping',
            old_name='resource',
            new_name='resource_id',
        ),
        migrations.RenameField(
            model_name='roleresourcemapping',
            old_name='role',
            new_name='role_id',
        ),
    ]
