# Generated by Django 3.2.4 on 2023-12-21 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20231221_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roleresourcemapping',
            old_name='resource_id',
            new_name='resource',
        ),
        migrations.RenameField(
            model_name='roleresourcemapping',
            old_name='role_id',
            new_name='role',
        ),
    ]
